systemChat "Group responding to ReinforcementRequest";
_grp = _this;
private _groupToReinforce = _grp getVariable ["dsm_reinforceing", grpNull];
private _targets = ((leader _groupToReinforce) nearTargets 400) select {(_x#2) == blufor && (leader _groupToReinforce knowsAbout _x # 4) > 0.5 };
{_grp reveal [_x # 4, (_groupToReinforce knowsAbout _x # 4)]} forEach _targets;
[_grp] call CBA_fnc_clearWaypoints;
private _wp = _grp addWaypoint [getpos leader _grp, -1];
private _wp = _grp addWaypoint [getpos leader _grp, -1];
_wp setWaypointBehaviour "AWARE";
_wp setWaypointSpeed "FULL";
_wp setWaypointCompletionRadius 100;
_wp setWaypointPosition (getpos leader _grp);
_wp setWaypointType "MOVE";
_grp setCurrentWaypoint _wp;
_wp = _grp addWaypoint [getpos leader _groupToReinforce, -1];
_wp setWaypointType "MOVE";
_wp setWaypointCompletionRadius 200;
_wp = _grp addWaypoint [getpos leader _groupToReinforce, -1];
_wp setWaypointType "SAD";
_wp setWaypointCompletionRadius 200;
_wp = _grp addWaypoint [getpos leader _groupToReinforce, -1];
_wp setWaypointType "MOVE";
_wp setWaypointStatements ["true", "(group this) setVariable ['dsm_reinforceing', grpNull]"];
_wp setWaypointCompletionRadius 50;